#!/usr/bin/env bash

#set -o errexit

# Add an exif tag to a picture
# 
# @param :
# - $1 : tag name
# - $2 : tag value
# - $3 : filename
add_tag() {
    # Check if tag already exist before adding it
    EXISTING_TAG=$(exiv2 -g "$1" -Pv "$3")
    EXIST=$(echo "${EXISTING_TAG};" | sed 's/, /;\n/g' | grep "$2;" | wc -l)
    if [[ ${EXIST} -eq 0 ]]; then
        exiv2 -M"set $1 $2" $3 
    fi
}

# Delete an EXIF tag
# 
# @param :
# - $1 : tag name
# - $2 : filename
delete_tag() {
    exiv2 -M"del $1" $2 
}

# Escape some special character
escape_character() {
    echo "${1}" | sed "s/[!@#$%^&*()-|{}]/\\\&/g"
}

# Split tag in subtag if they contains delimiter
# Apply those tags to image
update_tag_on_file() {

    if [[ "${ACTION}" = "del" ]]; then
        delete_tag "Xmp.lr.hierarchicalSubject" "$1"
        delete_tag "Xmp.dc.Subject" "$1"
    else 
        TAG_TO_ADD=""
        ESC_DELIMETER=$(escape_character ${DELIMETER})

        add_tag "Xmp.lr.hierarchicalSubject" "${TAG_NAME}" "$1"
        add_tag "Xmp.dc.Subject" "${TAG_NAME}" "$1"

        if [[ ${TAG_NAME} =~ .*${ESC_DELIMETER}.* ]]; then
            COUNT=$(echo "${TAG_NAME}" | grep -o "${DELIMETER}" | wc -l)
            I=$COUNT
            while [[ $I -gt 0 ]] ; do
                TAG_TO_ADD=$(echo "${TAG_NAME}" | cut -d${DELIMETER} -f1-${I})
                add_tag "Xmp.lr.hierarchicalSubject" "${TAG_TO_ADD}" "$1"
                I=$(($I - 1))
            done
        fi
    fi

}

rename_photo() {
    exiv2 -F -r"%Y-%m-%d_%H-%M-%S_$SUFFIX" rename $1 || true
}

# Loop on all images from source and add tag to them
rename_photos() {
    find "${SOURCE}" -mindepth 1 -maxdepth 1 -regex '.*NEF\|.*JPG\|.*jpg' | while read file; do rename_photo ${file}; done
}

# Loop on all images from source and add tag to them
update_tag_on_files() {
    find "${SOURCE}" -mindepth 1 -maxdepth 1 -regex '.*NEF\|.*JPG\|.*jpg' | while read file; do update_tag_on_file ${file}; done
}

# Tag pictures process
tag_argument() {
    while [ $# -gt 0 ]
    do
        case "$1" in
            --tag-name|-t)
                TAG_NAME="${2}"
                shift
                ;;
            --delimiter|-d)
                DELIMETER=${2}
                shift
                ;;
            --source|-s)
                SOURCE=${2}
                shift
                ;;
            --rm)
                ACTION="del"
                ;;
            *)
                echo "elsetag"
                exit 1
                ;;    
        esac
        shift
    done

    export TAG_NAME="${TAG_NAME}"
    export SOURCE="${SOURCE:-.}"
    export DELIMETER="${DELIMETER:-|}"
    export ACTION="${ACTION:-set}"

    update_tag_on_files
}

# Tag pictures process
rename_argument() {
    while [ $# -gt 0 ]
    do
        case "$1" in
            --suffix|-t)
                SUFFIX="${2}"
                shift
                ;;
            --source|-s)
                SOURCE=${2}
                shift
                ;;
            *)
                echo "elserename"
                exit 1
                ;;    
        esac
        shift
    done

    export SUFFIX="${SUFFIX}"
    export SOURCE="${SOURCE:-.}"

    rename_photos
}

# Loop on all arguments and identify what main action should be run
while [ $# -gt 0 ]
do
    case "$1" in
        tag)
            shift
            tag_argument $@
            break
            exit 0
            ;;
        rename)
            shift
            rename_argument $@
            break
            exit 0
            ;;
        import)
            echo "import"
            break
            exit 0
            ;;
        *)  
            echo "else"
            exit 1
            ;;
    esac
done